[tool.poetry]
name = "recipe tests"
version = "0.1.0"
description = ""
authors = ["bob"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "7.2.1"
beautifulsoup4 = "^4.11.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
